menu:
  Resume: /resume (bio and skills)
  Works: /works (Projects and works)
  Contact: /contact (get in touch)

widgets:
- search
- category
- tag

test:
  search: OI
  category:
  tag:

less:
  paths:
    - source/css

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
rss:
